blog/article/urls.py
from django.urls import path
from article import views


app_name = 'article'
urlpatterns = [
    path('', views.article, name='article'),
    path('articleCreate/', views.articleCreate, name='articleCreate'),
    path('articleRead/<int:articleId>/', views.articleRead, name='articleRead'),
    path('articleUpdate/<int:articleId>/', views.articleUpdate, name='articleUpdate'),
    path('articleDelete/<int:articleId>/', views.articleDelete, name='articleDelete'),
    path('articleSearch/', views.articleSearch, name='articleSearch'),
    path('articleLike/<int:articleId>/', views.articleLike, name='articleLike'),
    path('commentCreate/<int:articleId>/', views.commentCreate, name='commentCreate'),
    path('commentUpdate/<int:commentId>/', views.commentUpdate, name='commentUpdate'),
    path('commentDelete/<int:commentId>/', views.commentDelete, name='commentDelete'),
]

blog/blog/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from main import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls', namespace='account')),
    path('article/', include('article.urls', namespace='article')),
    path('main/', include('main.urls', namespace='main')),
    re_path('.*', views.main),
]

blog/article/models.py
from django.db import models
from account.models import User
# Create your models here.

class Article(models.Model):
    title = models.CharField(max_length=128, unique=True)
    content = models.TextField()
    pubDateTime = models.DateTimeField(auto_now_add=True)
    likes = models.ManyToManyField(User)
    
    def __str__(self):
        return self.title

    class Meta:
        ordering = ['-pubDateTime']

class Comment(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.CharField(max_length=128)
    pubDateTime = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return self.article.title + '-' + str(self.id)
    class Meta:
        ordering = ['-pubDateTime']

blog/article/forms.py
from django import forms
from article.models import Article


class ArticleForm(forms.ModelForm):
    title = forms.CharField(label='標題', max_length=128)
    content = forms.CharField(label='內容', widget=forms.Textarea)

    class Meta:
        model = Article
        fields = ['title', 'content']

blog/article/views.py
from django.shortcuts import render, redirect, get_object_or_404
from article.models import  Article, Comment
from article.forms import ArticleForm
from django.contrib import messages
from django.db.models.query_utils import Q
from django.contrib.auth.decorators import login_required
from main.views import admin_required

# Create your views here.
def article(request):
    '''
    Render the article page
    '''
    articles = {}
    for article in Article.objects.all():
        articles.update({ article:Comment.objects.filter(article = article)})
    context = {'articles' : articles}
    return render(request, 'article/article.html', context)

@admin_required
def articleCreate(request):
    '''
    Create a new article instance
        1. If method is GET, render an empty form
        2. If method is POST, perform form validation and display error messages if the form is invalid
        3. Save the form to the model and redirect the user to the article page
    '''
    # get
    template = 'article/articleCnU.html'
    if request.method == 'GET':
        return render(request, template, {'articleForm':ArticleForm()})

    # post
    articleForm = ArticleForm(request.POST)
    if not articleForm.is_valid():
        return render(request, template, {'articleForm':articleForm})

    articleForm.save()
    messages.success(request, '文章已新增')
    return redirect('article:article')


def articleRead(request, articleId):
    '''
    Read an article
        1. Get the "article" instance using "articleId"; redirect to the 404 page if not found
        2. Render the articleRead template with the article instance and its
           associated comments
    '''
    article = get_object_or_404(Article, id=articleId)
    context = {
        'article': article,
        'comments': Comment.objects.filter(article=article)
    }
    return render(request, 'article/articleRead.html', context)

@admin_required
def articleUpdate(request, articleId):
    '''
    Update the article instance:
        1. Get the article to update; redirect to 404 if not found
        2. Render a bound form if the method is GET
        3. If the form is valid, save it to the model, otherwise render a
           bound form with error messages
    '''
    article = get_object_or_404(Article, id=articleId)
    template = 'article/articleCnU.html'
    if request.method == 'GET':
        articleForm = ArticleForm(instance=article)
        return render(request, template, {'articleForm':articleForm})

    # POST
    articleForm = ArticleForm(request.POST, instance=article)
    if not articleForm.is_valid():
        return render(request, template, {'articleForm':articleForm})

    articleForm.save()
    messages.success(request, '文章已修改') 
    return redirect('article:articleRead', articleId=articleId)

@admin_required
def articleDelete(request, articleId):
    '''
     Delete the article instance:
        1. Render the article page if the method is GET
        2. Get the article to delete; redirect to 404 if not found
    '''
    if request.method == 'GET':
        return redirect('article:article')
    #post
    article = get_object_or_404(Article, id=articleId)
    article.delete()
    messages.success(request, '文章已刪除')
    return redirect('article:article')

def articleSearch(request):
    '''
    Search for articles:
        1. Get the "searchTerm" from the HTML page
        2. Use "searchTerm" for filtering
    '''
    searchTerm = request.GET.get('searchTerm')
    articles = Article.objects.filter(Q(title__icontains=searchTerm) |
                                      Q(content__icontains=searchTerm))
    context = {'articles':articles, 'searchTerm':searchTerm} 
    return render(request, 'article/articleSearch.html', context)

@login_required
def articleLike(request, articleId):
    '''
    Add the user to the 'likes' field:
        1. Get the article; redirect to 404 if not found
        2. If the user does not exist in the "likes" field, add him/her
        3. Finally, call articleRead() function to render the article
    
    :param request:
    :param articleId:
    '''
    article = get_object_or_404(Article, id=articleId)
    if request.user not in article.likes.all():
        article.likes.add(request.user)
    return articleRead(request, articleId)

@login_required    
def commentCreate(request, articleId):
    '''
    Create a comment for an article:
        1. Get the "comment" from the HTML form
        2. Store it to database
    '''
    if request.method == 'GET':
        return articleRead(request, articleId)

    # POST
    comment = request.POST.get('comment')
    if comment:
        comment = comment.strip()
    if not comment:
        return redirect('article:articleRead', articleId=articleId)

    article = get_object_or_404(Article, id=articleId)
    Comment.objects.create(article=article, user=request.user, content=comment)
    return redirect('article:articleRead', articleId=articleId)

@login_required
def commentUpdate(request, commentId):
    '''
    Update a comment:
        1. Get the comment to update and its article; redirect to 404 if not found
        2. If it is a 'GET' request, return
        3. If the comment's author is not the user, return
        4. If comment is empty, delete the comment, else update the comment
    '''
    commentToUpdate = get_object_or_404(Comment, id=commentId)
    article = get_object_or_404(Article, id=commentToUpdate.article.id)
    if request.method == 'GET':
        return articleRead(request, article.id)

    # POST
    if commentToUpdate.user != request.user:
        messages.error(request, '無修改權限')
        return redirect('article:articleRead', articleId=article.id)

    comment = request.POST.get('comment', '').strip()
    if not comment:
        commentToUpdate.delete()
    else:
        commentToUpdate.content = comment
        commentToUpdate.save()
    return redirect('article:articleRead', articleId=article.id)

@login_required
def commentDelete(request, commentId):
    '''
    Delete a comment:
        1. Get the comment to update and its article; redirect to 404 if not found
        2. If it is a 'GET' request, return
        3. If the comment's author is not the user, return
        4. Delete the comment
    '''
    comment = get_object_or_404(Comment, id=commentId)
    article = get_object_or_404(Article, id=comment.article.id)
    if request.method == 'GET':
        return articleRead(request, article.id)

    # POST
    if comment.user != request.user:
        messages.error(request, '無刪除權限')
        return redirect('article:articleRead', articleId=article.id)

    comment.delete()
    return redirect('article:articleRead', articleId=article.id)

blog/article/templates/article/article.html
{% extends 'main/base.html' %}
{% load staticfiles %}
{% block css %}
<link rel="stylesheet" href="{% static 'article/css/article.css' %}">
{% endblock %}
{% block heading %}歡迎蒞臨{% endblock %}
{% block content %}
{% include 'article/searchForm.html' %}
{% if user.is_superuser %}
<p class="inlineBlock"><a class="btn" href="{% url 'article:articleCreate' %}">新增文章</a></p>
{% endif %}
<br><br><hr>
{% for article, comments in articles.items %}
  <h3 class="inlineBlock"><a href="{% url 'article:articleRead' article.id %}">{{ article.title }}</a></h3>
  {% if user.is_superuser %}
    <form class="inlineBlock" method="post" action="{% url 'article:articleDelete' article.id %}">
      {% csrf_token %}
      <input class="btn deleteConfirm" type="submit" value="刪除">
    </form>
  {% endif %} 
  <p>發表時間：{{ article.pubDateTime|date:'Y-m-d H:i' }}</p>
  <div class="articleContent">{{ article.content|linebreaks|truncatechars_html:30 }}</div>
  <p class=like>
    <img id=like src="{% static 'main/img/like.png' %}" alt="Like"> {{ article.likes.count }}
  </p>
  {% for comment in comments %}
    <div class="commentDiv">
    <span class="commentAuthor">{{ comment.user.fullName }}</span>
      <span class="comment">{{ comment.content }}</span>
      <br>
      <span class="commentTime">{{ comment.pubDateTime|date:'m月d日 H:i' }}</span>
    </div>
  {% endfor %}
  <hr>
{% endfor %}
{% endblock %}
{% block script %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src={% static 'main/js/deleteConfirm.js' %}></script>
{% endblock %}

blog/article/templates/article/articleCnU.html
{% extends 'main/base.html' %}
{% load staticfiles %}
{% block css %}
<link rel="stylesheet" href="{% static 'article/css/article.css' %}">
{% endblock %}
{% block heading %}
  {% if articleForm.instance.id %}
    修改文章
  {% else %}
    新增文章
  {% endif %}
{% endblock %}
{% block content %}
{% if articleForm.instance.id %}
  <form method="post" action="{% url 'article:articleUpdate' articleForm.instance.id %}">
{% else %}
<form method="post" action="{% url 'article:articleCreate' %}">
{% endif %}
  {% csrf_token %}
  {{ articleForm.as_p }}
  <input type="submit" class="submit" value="送出">
  <a class="submit" href="{% url 'article:article' %}">放棄</a>
</form>
{% endblock %}

blog/article/templates/article/articleRead.html
{% extends 'main/base.html' %}
{% load staticfiles %}
{% block css %}
<link rel="stylesheet" href="{% static 'article/css/article.css' %}">
{% endblock %}
{% block heading %}閱讀文章{% endblock %}
{% block content %}
<h3 class="inlineBlock">{{ article.title }}</h3>
{% if user.is_superuser %}
  <a class="btn inlineBlock" href="{% url 'article:articleUpdate' article.id %}">修改</a>
{% endif %}
<p>發表時間：{{ article.pubDateTime|date:'Y-m-d H:i' }}</p>

<div class="articleContent">{{ article.content|linebreaks }}</div>
<p class=like>
    <img id=like src="{% static 'main/img/like.png' %}" alt="Like"> {{ article.likes.count }}
  {% if user.is_authenticated %}
    <a href="{% url 'article:articleLike' article.id %}">讚~</a>
  {% endif %}
</p>
{% for comment in comments %}
  <div class="commentDiv">
  <span class="commentAuthor">{{ comment.user.fullName }}</span>
  {% if comment.user != user %}
    <span class="comment">{{ comment.content }}</span>
    {% else %}
      <form class="inlineBlock" method="post" action="{% url 'article:commentUpdate' comment.id %}">
        {% csrf_token %}
        <input type="text" name="comment" value="{{ comment.content }}">
        <input class="btn" type="submit" value="修改">
      </form>
      <form class="inlineBlock" method="post" action="{% url 'article:commentDelete' comment.id %}">
        {% csrf_token %}
        <input class="btn deleteConfirm" type="submit" value="刪除">
      </form>
    {% endif %}
    <br>
    <span class="commentTime">{{ comment.pubDateTime|date:'Y-m-d H:i'}}</span>
  </div>
{% endfor %}
{% if user.is_authenticated %}
  <br>
  <form method="post" action="{% url 'article:commentCreate' article.id %}">
    {% csrf_token %}
    <input type="text" name="comment"  placeholder="留言 ...">
    <input class="btn" type="submit" value="送出">
  </form>
  <br><br>
{% endif %}
<a class="submit" href="{% url 'article:article' %}">回文章列表</a>
{% endblock %}
{% block script %}
  <script src="{% static 'main/js/deleteConfirm.js' %}"></script>
{% endblock %}

blog/article/templates/article/articleSearch.html
{% extends 'main/base.html' %}
{% load staticfiles %}
{% block css %}
<link rel="stylesheet" href="{% static 'article/css/article.css' %}">
{% endblock %}
{% block heading %}搜尋{% endblock %}
{% block content %}
{% include 'article/searchForm.html' %}
<br><br><hr>
{% if not articles %}
  <p>查無資料</p>
{% else %}
  <table class="table table-striped table-hover">
    <tr><th>標題</th><th>發表時間</th></tr>
    {% for article in articles %}
    <tr>
      <td><a href="{% url 'article:articleRead' article.id %}">{{ article.title }}</a></td>
      <td>{{ article.pubDateTime|date:'Y-m-d H:i' }}</td>
    </tr>
    {% endfor %}
  </table>
{% endif %}
{% endblock %}

blog/article/templates/article/searchForm.html
<form class="inlineBlock" action="{% url 'article:articleSearch' %}">
  <input type="text" name="searchTerm" {% if searchTerm %}value="{{ searchTerm }}"{% endif %}>
  <input class="btn" type="submit" value="查詢">
</form>